declare module '*.module.css'
declare module 'react-dropzone'
declare module '@dhis2/analytics'
declare module 'file-saver'
declare module 'jszip'
declare module 'openapi-typescript-codegen'
declare module '@dhis2/app-adapter'
declare module '@dhis2/d2-i18n'
